import { writable } from 'svelte/store';
export const meritAdminValues = writable([]);
export const meritModalDate = writable('');
export const meritIncidentDateValue = writable('');
export const meritModalSelectedCategory = writable('');
export const meritModalBehaviors = writable([]);
export const meritModalTeacherName = writable('');
export const meritModalSubject = writable('');
export const meritModalStudentName = writable('');
export const meritModalStudentId = writable('');
export const meritModalStudentCategory = writable('');
export const meritModalStudentDetails = writable('');
export const meritModalTeachers = writable([]);
